"""Add Booster model

Revision ID: ac9c7e5a428d
Revises: d6dfd06c0cd2
Create Date: 2023-04-27 01:31:49.048641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9c7e5a428d'
down_revision = 'd6dfd06c0cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('deck_name', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_name'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boosters')
    # ### end Alembic commands ###
